---

  # ansible.builtin.shell: |
  #   firewall-cmd --permanent --add-port=6443/tcp
  #   firewall-cmd --permanent --add-port=2379-2380/tcp
  #   firewall-cmd --permanent --add-port=10250/tcp
  #   firewall-cmd --permanent --add-port=10251/tcp
  #   firewall-cmd --permanent --add-port=10252/tcp
  #   firewall-cmd --permanent --add-port=10255/tcp
  #   firewall-cmd --permanent --add-port=8472/udp
  #   firewall-cmd --permanent --add-port=30000-32767/tcp

- name: Setting Firewalld Master
  ansible.posix.firewalld:
    port: "{{ item.port }}/{{ item.proto }}"
    permanent: true
    state: enabled
  with_items:
    - {port: "6443", proto: "tcp"}
    - {port: "2379-2380", proto: "tcp"}
    - {port: "10251", proto: "tcp"}
    - {port: "10252", proto: "tcp"}

- name: Reload service firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

- name: Init Cluster
  ansible.builtin.command: kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --pod-network-cidr=10.244.0.0/16
  changed_when: false
  when: HOST_COUNT == "1"

- name: Init Cluster Multiple Master
  ansible.builtin.command: kubeadm init --control-plane-endpoint="{{ END_POINT }}" --upload-certs --apiserver-advertise-address={{ ansible_default_ipv4.address }} --pod-network-cidr=10.244.0.0/16
  changed_when: false
  when: HOST_COUNT > "1"

- name: Setting Kube Config
  ansible.builtin.shell: |
    mkdir -p $HOME/.kube
    sudo cp -if /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config
  changed_when: false

- name: Get Certificate for join cluster
  ansible.builtin.command: kubeadm init phase upload-certs --upload-certs
  changed_when: false
  register: upload_certs
  when: HOST_COUNT > "1"

- name: Get Command join Master in cluster
  ansible.builtin.command: kubeadm token create --certificate-key {{ upload_certs.stdout_lines[2] }} --print-join-command
  changed_when: false
  register: master_join
  when: HOST_COUNT > "1"

- name: Kubernetes create token for join
  ansible.builtin.command: kubeadm token create --print-join-command
  register: worker_join
  changed_when: false

- name: "Set Cmd Join Cluster"
  ansible.builtin.add_host:
    name: "master01"
    worker-join: "{{ worker_join.stdout }}"
    master-join: "{{ master_join.stdout }}"

- name: Install Network Plugin
  ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  changed_when: false
